<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <EmbeddedResource Include="logo.png" />
        <EmbeddedResource Include="BazaarLogicMod.dll" />
    </ItemGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  
  <Target Name="CopyCustomLauncherToPublish" AfterTargets="Publish">
    <Message Text="Copying customlauncher.bat, README, and BepInEx zip to publish folder" Importance="high" />
    <Copy
            SourceFiles="../customlauncher.bat;../Readme-what is this.txt;BepInEx_win_x64_5.4.23.5.zip"
            DestinationFolder="$(PublishDir)"
            SkipUnchangedFiles="true" />
  </Target>
  <Target Name="CopyToBazaarLogicMod" AfterTargets="Build">
    <Message Text="Copying BazaarLogicMod.dll to $(PublishDir)" Importance="high" />
    <Copy
            SourceFiles="BazaarLogicMod.dll"
            DestinationFolder="$(PublishDir)"
            SkipUnchangedFiles="true" />
  </Target>
</Project>
